BlackBoardApp/src/main/java/by/mmf/blackboardm/view/CalendarBean.java
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package by.mmf.blackboardm.view;

import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.io.OutputStream;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import javax.imageio.ImageIO;

/**
 *
 * @author jack
 */
@ManagedBean(name = "calendarBean")
@SessionScoped
public class CalendarBean {

    private String imgPath = "JavaKaffe";

    public String getImgPath() {
        return imgPath;
    }

    public String getRealImgPath() {
        if (!imgPath.equals("JavaKaffe")) {
            return "p2.jpg";
        }
        return imgPath + ".jpg";
    }

    public void setImgPath(String imgPath) {
        this.imgPath = imgPath;
    }
}

BlackBoardApp/src/main/webapp/index.jsp
<%-- 
    Document   : index
    Created on : Jan 7, 2013, 11:11:00 PM
    Author     : jack
--%>

<%@page contentType="text/html" pageEncoding="UTF-8"%>
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>JSP Page</title>
    </head>
    <body>
        <h1>Hello World!</h1>
        <a href="faces/index.xhtml" >to faces page</a>
    </body>
</html>

BlackBoardApp/src/main/webapp/index.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:a4j="http://richfaces.org/a4j"
      xmlns:rich="http://richfaces.org/rich"> 
    <ui:composition template="/templates/main.xhtml">
        <ui:define name="content">
            <h:form>
                <h:outputText value="heee.."/>
                <h:panelGrid>
                    <h:inputText id="imgPathInT" value="#{calendarBean.imgPath}">
                        <f:ajax event="blur" render="img" />
                    </h:inputText>
                    <h:graphicImage id="img" library="images" name="#{calendarBean.realImgPath}" width="150"/>
                </h:panelGrid>
            </h:form>
        </ui:define>

    </ui:composition>
</html>

BlackBoardApp/src/main/webapp/templates/main.xhtml
<?xml version='1.0' encoding='UTF-8' ?> 
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:h="http://java.sun.com/jsf/html">

    <h:head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <link href="./../resources/css/default.css" rel="stylesheet" type="text/css" />
        <link href="./../resources/css/cssLayout.css" rel="stylesheet" type="text/css" />
        <title>Facelets Template</title>
    </h:head>

    <h:body>

        <div id="top">
            <ui:insert name="top">Top</ui:insert>
        </div>

        <div id="content" class="center_content">
            <ui:insert name="content">Content</ui:insert>
        </div>

        <div id="bottom">
            <ui:insert name="bottom">Bottom</ui:insert>
        </div>

    </h:body>

</html>